import axiosInstance from "./api";
import { deriveVaultKeyFromPassword, generateKdfSalt } from "./vaultCrypto";

// The raw vault key never goes into localStorage (that's the same storage
// the JWT lives in -- an XSS reading one already reads the other) --
// sessionStorage instead, so it's gone the moment the tab closes and the
// next visit does a fresh recover round-trip.
const VAULT_KEY_STORAGE = "passvault.vaultKey";

const readCachedKey = () => {
  if (typeof window === "undefined") return null;
  try {
    return sessionStorage.getItem(VAULT_KEY_STORAGE);
  } catch {
    return null;
  }
};

const cacheKey = (vaultKey) => {
  if (typeof window === "undefined") return;
  try {
    sessionStorage.setItem(VAULT_KEY_STORAGE, vaultKey);
  } catch {
    // Private browsing / storage disabled: the key just won't survive a refresh.
  }
};

// Read-only check -- never creates a key. Used to gate the dashboard (no
// key yet -> send the client to /profile to set one up) and to drive the
// "Set up"/"ready" badge on the Profile page itself.
export const getVaultKeyStatus = async () => {
  const cached = readCachedKey();
  if (cached) return { exists: true, vaultKey: cached };

  try {
    const { result } = await axiosInstance.post("/vault/key/recover");
    cacheKey(result.vaultKey);
    return { exists: true, vaultKey: result.vaultKey };
  } catch (err) {
    if (err?.message?.includes("No escrowed vault key")) {
      return { exists: false, vaultKey: null };
    }
    throw err;
  }
};

// The one-time, explicit setup action (Profile page's "Set up vault key"
// form) -- the vault key is derived from a password the CLIENT chooses
// (never generated by us), then escrowed server-side via POST
// /vault/key/setup (wrapped with PassVaultapi's VAULT_MASTER_KEY, see its
// utilities/vaultCrypto.js). Every later visit, on any device, recovers
// this same key via getVaultKeyStatus above.
export const setupVaultKey = async (vaultPassword) => {
  const kdfSalt = generateKdfSalt();
  const vaultKey = await deriveVaultKeyFromPassword(vaultPassword, kdfSalt);
  await axiosInstance.post("/vault/key/setup", { vaultKey, kdfSalt });
  cacheKey(vaultKey);
  return vaultKey;
};

// Used once the dashboard has already confirmed (via getVaultKeyStatus)
// that a key exists -- throws rather than silently creating one, since
// creation only ever happens through the explicit Profile-page action above.
export const requireVaultKey = async () => {
  const { exists, vaultKey } = await getVaultKeyStatus();
  if (!exists) {
    throw new Error("Vault encryption key is not set up yet -- set it up on your Profile page first.");
  }
  return vaultKey;
};

export const clearCachedVaultKey = () => {
  if (typeof window === "undefined") return;
  try {
    sessionStorage.removeItem(VAULT_KEY_STORAGE);
  } catch {
    // ignore
  }
};
