// Client-side AES-256-GCM for vault entries. The blob PassVaultapi stores in
// each client's own Google Drive (see GET/PUT /vault/data in vaultData.js)
// is opaque to the server -- it never decrypts it, only relays it -- so all
// encryption has to happen here, in the browser, with WebCrypto.
const IV_LENGTH = 12; // bytes, standard nonce size for AES-GCM

const toBase64 = (bytes) => btoa(String.fromCharCode(...new Uint8Array(bytes)));
const fromBase64 = (b64) => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));

// The KDF salt is public (not secret) but must be random and unique per
// client -- it's generated once at setup and stored alongside the escrowed
// key server-side (tblClientVaultKey.wrKdfSalt) purely for record-keeping,
// since PBKDF2 needs the exact same salt to re-derive the same key.
export const generateKdfSalt = () => toBase64(crypto.getRandomValues(new Uint8Array(16)));

// OWASP-recommended minimum for PBKDF2-HMAC-SHA256 (2023 guidance).
const PBKDF2_ITERATIONS = 210000;

// The vault key is never generated by us -- it's derived from a password
// the client chooses (VaultKeySetup's "Vault password" field), so the
// secret's origin is entirely client-side. PBKDF2 stretches that password
// against the KDF salt into the 256-bit AES key actually used to
// encrypt/decrypt entries.
export const deriveVaultKeyFromPassword = async (vaultPassword, kdfSaltBase64) => {
  const salt = fromBase64(kdfSaltBase64);
  const baseKey = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(vaultPassword),
    "PBKDF2",
    false,
    ["deriveBits"]
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations: PBKDF2_ITERATIONS, hash: "SHA-256" },
    baseKey,
    256
  );
  return toBase64(bits);
};

const importKey = (vaultKeyBase64) =>
  crypto.subtle.importKey("raw", fromBase64(vaultKeyBase64), "AES-GCM", false, ["encrypt", "decrypt"]);

// Returns one base64 string (iv + ciphertext concatenated) so the blob PUT
// to /vault/data is self-contained -- nothing else needs to travel with it.
export const encryptVaultBlob = async (vaultKeyBase64, plaintextObject) => {
  const key = await importKey(vaultKeyBase64);
  const iv = crypto.getRandomValues(new Uint8Array(IV_LENGTH));
  const plaintext = new TextEncoder().encode(JSON.stringify(plaintextObject));
  const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, plaintext);
  const combined = new Uint8Array(iv.length + ciphertext.byteLength);
  combined.set(iv, 0);
  combined.set(new Uint8Array(ciphertext), iv.length);
  return toBase64(combined);
};

export const decryptVaultBlob = async (vaultKeyBase64, blobBase64) => {
  const key = await importKey(vaultKeyBase64);
  const combined = fromBase64(blobBase64);
  const iv = combined.slice(0, IV_LENGTH);
  const ciphertext = combined.slice(IV_LENGTH);
  const plaintext = await crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, ciphertext);
  return JSON.parse(new TextDecoder().decode(plaintext));
};
