"use client";

import { useEffect, useState } from "react";
import { Alert, Badge, FormGroup, Input, Label } from "reactstrap";
import { getVaultKeyStatus, setupVaultKey } from "@/lib/vaultKey";
import { isPasswordStrongEnough } from "@/utils/passwordStrength";
import PasswordStrengthMeter from "@/components/PasswordStrengthMeter";

// One-time setup: the client picks a vault password here -- it is never
// generated by us. That password is stretched (PBKDF2) into the AES-256
// key used to encrypt/decrypt every account (see vaultCrypto.js), then the
// derived key is escrowed server-side (wrapped, see PassVaultapi's
// utilities/vaultCrypto.js) via POST /vault/key/setup. The server only
// ever stores/relays ciphertext and the wrapped key -- never this password.
export default function VaultKeySetup({ onReady }) {
  const [status, setStatus] = useState("loading"); // "loading" | "ready" | "missing" | "error"
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [isSettingUp, setIsSettingUp] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    getVaultKeyStatus()
      .then(({ exists }) => {
        if (cancelled) return;
        setStatus(exists ? "ready" : "missing");
        if (exists) onReady?.();
      })
      .catch(() => {
        if (!cancelled) setStatus("error");
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- run once on mount only
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);

    if (!isPasswordStrongEnough(password)) {
      setError("Please choose a stronger vault password (see the strength meter below).");
      return;
    }
    if (password !== confirmPassword) {
      setError("Vault password and confirmation do not match.");
      return;
    }

    setIsSettingUp(true);
    try {
      await setupVaultKey(password);
      setPassword("");
      setConfirmPassword("");
      setStatus("ready");
      onReady?.();
    } catch (err) {
      setError(err?.message || "Could not set up your vault key. Please try again.");
    } finally {
      setIsSettingUp(false);
    }
  };

  return (
    <div>
      <div className="d-flex align-items-center justify-content-between flex-wrap gap-2 mb-2">
        <div className="fw-semibold">Vault encryption key</div>

        {status === "loading" ? (
          <Badge color="secondary">Checking...</Badge>
        ) : status === "ready" ? (
          <Badge color="success">
            <i className="bx bx-check me-1" />
            Set up
          </Badge>
        ) : status === "error" ? (
          <Badge color="secondary">Unable to check status</Badge>
        ) : null}
      </div>

      {status === "missing" ? (
        <form onSubmit={handleSubmit}>
          <p className="text-muted small">
            Choose a vault password -- it never leaves your device as plain text. It&apos;s stretched into the
            key that encrypts every account you save.
          </p>

          {error ? (
            <Alert color="danger" className="py-2 px-3">
              {error}
            </Alert>
          ) : null}

          <FormGroup>
            <Label className="form-label">Vault password</Label>
            <Input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required />
            <PasswordStrengthMeter password={password} />
          </FormGroup>

          <FormGroup>
            <Label className="form-label">Confirm vault password</Label>
            <Input
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              required
            />
          </FormGroup>

          <button type="submit" className="btn btn-primary btn-sm" disabled={isSettingUp}>
            {isSettingUp ? "Setting up..." : "Set up vault key"}
          </button>
        </form>
      ) : (
        <div className="text-muted small">
          Encrypts every account you save. A wrapped copy is escrowed on our server so you can recover it on
          another device.
        </div>
      )}
    </div>
  );
}
